
services:
  lfs-docker:
    container_name: lfs-docker
    tty: true
    privileged: true
    cap_add:
      - SYS_ADMIN
    hostname: lfs-docker
    build:
      context: ./srcs
    env_file:
      - .config
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/fuse:/dev/fuse
    volumes:
      - ./mnt:/mnt
      - lfs_persist:/persist
      - lfs_srcs:/home/lfs/srcs

volumes:
  lfs_persist:
    name: lfs-persist
    driver: local
    driver_opts:
      type: none
      device: ./persist
      o: bind
  lfs_srcs:
    name: lfs-srcs
    driver: local
    driver_opts:
      type: none
      device: ./srcs
      o: bind
